import type { Metadata } from "next";
import { LegalPage } from "@/components/Legal";
import { LEGAL } from "@/lib/legal";
export const metadata: Metadata = { title: "Privacy Policy — Office Pick'em League" };
const C = LEGAL.companyName;
export default function Privacy() {
  return <LegalPage title="Privacy Policy" sections={[
    { p: [`This Privacy Policy explains how ${C} ("we," "us") collects, uses, and shares information when you use our website, web app, text-message, and phone services (the "Service").`] },
    { h: "1. Information we collect", p: [`Information you provide: your name and (if you play by text) your mobile number; the 4-digit PIN you set; and the picks and settings you submit. A Commissioner provides the League name and may add branding or roster information.`, `Information created by using the Service: your picks, scores, standings, basic usage events, and the date/time you consented to receive texts.`, `Information collected automatically: standard technical data such as device/browser type and IP address, used to operate and secure the Service. The Service is not directed to anyone under 18.`] },
    { h: "2. How we use information", p: [`To operate the game (record picks, compute scores and standings); send the messages you opted into (reminders, game lines, results) by text, web, email, or phone; provide the Commissioner's admin and engagement views for their own League; maintain security; and improve the Service.`] },
    { h: "3. Text messaging", p: [`If you opt in, we send recurring automated text messages related to your League. Consent is collected via a clear checkbox (or by texting JOIN) and is not a condition of anything. Reply STOP to opt out, HELP for help. We do not share mobile numbers or text-message consent with third parties for their marketing. See our SMS Program Terms.`] },
    { h: "4. How we share information", p: [`Within your League: your name, results, and standings are visible to other participants and your Commissioner — that is how the game works.`, `Service providers: vendors that run the Service (cloud hosting, our database provider, our SMS/voice provider) process information on our behalf under contract.`, `Legal: we may disclose information if required by law or to protect rights and safety.`, `We do not sell your personal information and do not share it for third-party marketing. Any product we may build from gameplay data is opt-in, aggregated/de-identified, and kept separate from any individual's workplace information.`] },
    { h: "5. Data security and retention", p: [`We use reasonable administrative and technical safeguards (including encryption in transit and access controls), consistent with applicable data-security laws such as the New York SHIELD Act. No system is perfectly secure. We retain information as long as needed to provide the Service and for legitimate business or legal purposes, then delete or de-identify it.`] },
    { h: "6. Your choices and rights", p: [`Texts: reply STOP to opt out anytime; START to opt back in. Access/deletion: email ${LEGAL.email} to request a copy or deletion of your personal information; residents of certain states may have additional rights, which we honor where applicable. Commissioners can remove players and reset PINs in their admin console.`] },
    { h: "7. Children", p: [`The Service is for adults 18 and over and is not intended for children. We do not knowingly collect information from anyone under 18. If you believe a minor provided information, contact us and we will delete it.`] },
    { h: "8. Changes & contact", p: [`We may update this Policy and will post the new version with an updated effective date. ${C}${LEGAL.address ? ` · ${LEGAL.address}` : ""} · ${LEGAL.email}.`] },
  ]} />;
}
